version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: lemon-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: lemon
      POSTGRES_PASSWORD: lemon
      POSTGRES_DB: lemondb
    ports:
      - "5432:5432"
    volumes:
      - lemon_pgdata:/var/lib/postgresql/data
    networks:
      - lemon_net

volumes:
  lemon_pgdata:

networks:
  lemon_net:
    driver: bridge